name: "release"

on:
  push:
    branches:
      - "master"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
   
      - name: "Create Zip"
        run: zip -r ass6.zip src build.xml

      - name: "Create Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Assignment Zip"
          files: ass6.zip